"""Phase A: provider ID mapping, box scores, live game state snapshots.

Revision ID: 0001_phase_a
Revises:
Create Date: 2026-07-30

Written by hand rather than autogenerated, on purpose. The existing tables
(teams, games, users, play_by_play) were created by Base.metadata.create_all
and are already live in production, so this migration must ONLY add the new
tables and the one new column. Autogenerate against a fresh database would have
tried to create the existing four as well.

Safe to run against the live Render database: every operation is additive.
"""

from alembic import op
import sqlalchemy as sa

revision = "0001_phase_a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ---- games.tipoff_utc -------------------------------------------------
    # The column create_all could never have added, because `games` exists.
    op.add_column(
        "games",
        sa.Column("tipoff_utc", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_games_tipoff_utc", "games", ["tipoff_utc"])

    # ---- provider identity mapping ---------------------------------------
    op.create_table(
        "team_external_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_id", sa.String(length=40), nullable=False),
        sa.Column("provider_abbreviation", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_id", name="uq_team_ext_provider_id"),
        sa.UniqueConstraint("team_id", "provider", name="uq_team_ext_team_provider"),
    )
    op.create_index("ix_team_external_ids_id", "team_external_ids", ["id"])
    op.create_index("ix_team_external_ids_team_id", "team_external_ids", ["team_id"])

    op.create_table(
        "game_external_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_id", name="uq_game_ext_provider_id"),
        sa.UniqueConstraint("game_id", "provider", name="uq_game_ext_game_provider"),
    )
    op.create_index("ix_game_external_ids_id", "game_external_ids", ["id"])
    op.create_index("ix_game_external_ids_game_id", "game_external_ids", ["game_id"])

    # ---- players ----------------------------------------------------------
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=80), nullable=False),
        sa.Column("first_name", sa.String(length=40), nullable=True),
        sa.Column("last_name", sa.String(length=40), nullable=True),
        sa.Column("position", sa.String(length=8), nullable=True),
        sa.Column("jersey_number", sa.String(length=4), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_players_id", "players", ["id"])
    op.create_index("ix_players_full_name", "players", ["full_name"])

    op.create_table(
        "player_external_ids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_id", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_id", name="uq_player_ext_provider_id"),
        sa.UniqueConstraint(
            "player_id", "provider", name="uq_player_ext_player_provider"
        ),
    )
    op.create_index("ix_player_external_ids_id", "player_external_ids", ["id"])
    op.create_index(
        "ix_player_external_ids_player_id", "player_external_ids", ["player_id"]
    )

    # ---- box scores -------------------------------------------------------
    op.create_table(
        "player_game_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("seconds_played", sa.Integer(), nullable=True),
        sa.Column("started", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("points", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fgm", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fga", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fg3m", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fg3a", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("ftm", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fta", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("oreb", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("dreb", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("assists", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("steals", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("blocks", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("turnovers", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fouls", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("plus_minus", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"]),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"]),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "player_id", name="uq_pgs_game_player"),
    )
    op.create_index("ix_player_game_stats_id", "player_game_stats", ["id"])
    op.create_index("ix_player_game_stats_game_id", "player_game_stats", ["game_id"])
    op.create_index("ix_player_game_stats_player_id", "player_game_stats", ["player_id"])
    op.create_index("ix_player_game_stats_team_id", "player_game_stats", ["team_id"])

    op.create_table(
        "team_game_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("is_home", sa.Boolean(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fgm", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fga", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fg3m", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fg3a", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("ftm", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fta", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("oreb", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("dreb", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("assists", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("steals", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("blocks", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("turnovers", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("fouls", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("team_rebounds", sa.Integer(), nullable=True),
        sa.Column("team_turnovers", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"]),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "team_id", name="uq_tgs_game_team"),
    )
    op.create_index("ix_team_game_stats_id", "team_game_stats", ["id"])
    op.create_index("ix_team_game_stats_game_id", "team_game_stats", ["game_id"])
    op.create_index("ix_team_game_stats_team_id", "team_game_stats", ["team_id"])

    # ---- live game state --------------------------------------------------
    op.create_table(
        "game_state_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("period", sa.Integer(), nullable=False),
        sa.Column("clock", sa.String(length=16), nullable=True),
        sa.Column("score_home", sa.Integer(), nullable=False),
        sa.Column("score_away", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "period", "clock", name="uq_snapshot_moment"),
    )
    op.create_index("ix_game_state_snapshots_id", "game_state_snapshots", ["id"])
    op.create_index(
        "ix_game_state_snapshots_game_id", "game_state_snapshots", ["game_id"]
    )
    op.create_index(
        "ix_game_state_snapshots_captured_at", "game_state_snapshots", ["captured_at"]
    )


def downgrade() -> None:
    op.drop_table("game_state_snapshots")
    op.drop_table("team_game_stats")
    op.drop_table("player_game_stats")
    op.drop_table("player_external_ids")
    op.drop_table("players")
    op.drop_table("game_external_ids")
    op.drop_table("team_external_ids")
    op.drop_index("ix_games_tipoff_utc", table_name="games")
    op.drop_column("games", "tipoff_utc")
